#!/bin/bash

if [ "$DB" != 'mariadb' ]
then
  echo "****************************************************************************"
  echo "** Attempted to load mariadb include with wrong DB field ${DB}"
  echo "****************************************************************************"
  exit 1
fi

DBPREFIX=${DBPREFIX:-'p_'}
DBNAME=${DBNAME:-'moodle'}
DBUSER=${DBUSER:-'moodle'}
DBPASS=${DBPASS:-'moodle'}

DBIMAGE="mariadb:${DBVERSION}"

docker run \
  # Use the network for this unique run
  --network "${NETWORK}" \
  # Detach after launcing
  -d \
  # Remain interactive
  -i \
  # Remove when done
  --rm \
  # Use a known name instead of linking
  --name="$HOST_DB" \
  # Use a tmpfs for the data directory
  --tmpfs /var/lib/mysql:rw \
  # Set the supplied params
  -e MYSQL_ROOT_PASSWORD=moodle -e MYSQL_DATABASE=${DBNAME} -e MYSQL_USER=${DBUSER} -e MYSQL_PASSWORD=${DBPASS} \ 
  # The image
  ${DBIMAGE}
  -d \
  -i \
  --rm \
  --name="$DOCKER_DB" \
  --tmpfs /var/lib/mysql:rw \
  --network "${NETWORK}" \
  $DBTYPE_ARGS
sleep 25
docker exec -it "${HOST_DB}" sh -c 'exec echo "SET GLOBAL innodb_large_prefix=1; " | mysql -u root --password=moodle ${DBNAME}'
docker exec -it "${HOST_DB}" sh -c 'exec echo "SET GLOBAL innodb_file_per_table=1; " | mysql -u root --password=moodle ${DBNAME}'
docker exec -it "${HOST_DB}" sh -c 'exec echo "SET GLOBAL innodb_file_format=Barracuda; " | mysql -u root --password=moodle ${DBNAME}'
