#!/bin/bash

if [ "$DB" != 'pgsql' ]
then
  echo "****************************************************************************"
  echo "** Attempted to load postgres include with wrong DB field ${DB}"
  echo "****************************************************************************"
  exit 1
fi

DBPREFIX=${DBPREFIX:-'p_'}
DBNAME=${DBNAME:-'moodle'}
DBUSER=${DBUSER:-'moodle'}
DBPASS=${DBPASS:-'moodle'}
DBVERSION=${DBVERSION:-'latest'}
DBSCRIPTS="${INCPATH}/databases/pgsql.d"

DBIMAGE="postgres:${DBVERSION}"

docker run \
  `# Use the network for this unique run` \
  --network "${NETWORK}" \
  `# Detach after launcing` \
  -d \
  `# Remain interactive` \
  -i \
  `# Remove when done` \
  --rm \
  `# Use a known name instead of linking` \
  --name="$HOST_DB" \
  `# Mount the postgres docker entrypoint folder to allow for post-setup tuning` \
  -v "${DBSCRIPTS}":/docker-entrypoint-initdb.d \
  `# Use a tmpfs for the postgres data directory` \
  --tmpfs /var/lib/postgresql/data:rw \
  `# Set the supplied params` \
  -e POSTGRES_USER=${DBUSER} -e POSTGRES_PASSWORD=${DBPASS} -e POSTGRES_DB=${DBNAME} \
  `# The image` \
  ${DBIMAGE}
