#!/bin/bash

if [ "$DB" != 'pgsql' ]
then
  echo "****************************************************************************"
  echo "** Attempted to load postgres include with wrong DB field ${DB}"
  echo "****************************************************************************"
  exit 1
fi

DB_SCRIPTS="${INCPATH}/databases/pgsql.d"

DB_IMAGE="postgres:${DB_VERSION}"
DB_IMAGE_OPTS="-e POSTGRES_USER=${DB_USER} -e POSTGRES_PASSWORD=${DB_PASS} -e POSTGRES_DB=${DB_NAME} -v ${DB_SCRIPTS}:/docker-entrypoint-initdb.d"
DB_IMAGE_TMPFS="--tmpfs /var/lib/postgresql/data:rw"
